import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Image from "next/image";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-white py-[10px] px-[80px]`}>
        <Header />
        <section className="w-full flex items-center space-x-20 bg-[#F6FBFF]">
          <Image
            src={"/1.webp"}
            alt="1.webp"
            width={500}
            height={500}
            className="w-[700px] h-[700px] object-cover"
          />
          {children}
        </section>
      </body>
    </html>
  );
}
